export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";


export const POST_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export const POST_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const POST_COMMENTS_FAIL = "GET_COMMENTS_FAIL";

export const DELETE_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export const DELETE_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const DELETE_COMMENTS_FAIL = "GET_COMMENTS_FAIL";


export const GET_COMMENT_ID_REQUEST = "GET_COMMENT_ID_REQUEST";
export const GET_COMMENT_ID__SUCCESS = "GET_COMMENT_ID__SUCCESS";
export const GET_COMMENT_ID__FAIL = "GET_COMMENT_ID__FAIL";
